export const raw = [
  {
    firstName: "Dolph",
    lastName: "Harmeston",
    email: "dharmeston0@elpais.com",
    password: "2ZVKVNSl5FJ",
  },
  {
    firstName: "Orsa",
    lastName: "Gorvette",
    email: "ogorvette1@paginegialle.it",
    password: "cpHFdQg",
  },
  {
    firstName: "Nettie",
    lastName: "Bisiker",
    email: "nbisiker2@pcworld.com",
    password: "GpfCvRynJPSf",
  },
  {
    firstName: "Rose",
    lastName: "Cooper",
    email: "rcooper3@unesco.org",
    password: "5JXlnln",
  },
  {
    firstName: "Francene",
    lastName: "MacPike",
    email: "fmacpike4@fc2.com",
    password: "FArkoT",
  },
  {
    firstName: "Dotty",
    lastName: "Mableson",
    email: "dmableson5@woothemes.com",
    password: "UvZzaQwP4wv",
  },
  {
    firstName: "Editha",
    lastName: "Swayton",
    email: "eswayton6@topsy.com",
    password: "jRK8cDIAoD",
  },
  {
    firstName: "Zorana",
    lastName: "Voysey",
    email: "zvoysey7@1688.com",
    password: "Ost8jAc7",
  },
  {
    firstName: "Marthe",
    lastName: "Ruzicka",
    email: "mruzicka8@businessinsider.com",
    password: "vo7KxaqE8UTb",
  },
  {
    firstName: "Dagmar",
    lastName: "Baradel",
    email: "dbaradel9@alibaba.com",
    password: "IpqqUh",
  },
  {
    firstName: "Arthur",
    lastName: "Mattheis",
    email: "amattheisa@cornell.edu",
    password: "IcM1LgHVr4CA",
  },
  {
    firstName: "Alfons",
    lastName: "Eltune",
    email: "aeltuneb@pinterest.com",
    password: "21sgBlaM1Tn",
  },
  {
    firstName: "Neil",
    lastName: "Pellissier",
    email: "npellissierc@stumbleupon.com",
    password: "7HzeznBDZIYb",
  },
  {
    firstName: "Montgomery",
    lastName: "Ivashin",
    email: "mivashind@about.com",
    password: "6g4PmiK",
  },
  {
    firstName: "Anya",
    lastName: "Scrafton",
    email: "ascraftone@nba.com",
    password: "zmwUb1Y",
  },
  {
    firstName: "Erika",
    lastName: "Pourvoieur",
    email: "epourvoieurf@cmu.edu",
    password: "RdGbhQ",
  },
  {
    firstName: "Buffy",
    lastName: "Thying",
    email: "bthyingg@loc.gov",
    password: "ibr8EZS",
  },
  {
    firstName: "Erena",
    lastName: "Ros",
    email: "erosh@ycombinator.com",
    password: "OopWT5csJ",
  },
  {
    firstName: "Rozamond",
    lastName: "Kneel",
    email: "rkneeli@webeden.co.uk",
    password: "Gh0VQiCJh",
  },
  {
    firstName: "Idette",
    lastName: "Krienke",
    email: "ikrienkej@flickr.com",
    password: "dvl06g4SW",
  },
];
