import { Role } from "@prisma/client";

export const raw = [
  { email: "tmahy0@dedecms.com", role: Role.SELLER, password: "YQMeUj38" },
  { email: "lbastistini1@epa.gov", role: Role.SELLER, password: "Ra33XNrt" },
  { email: "ssamsonsen2@imgur.com", role: Role.SELLER, password: "MCjYmPY" },
  { email: "eclifton3@cafepress.com", role: Role.BUYER, password: "FFNJfK" },
  { email: "cgorges4@is.gd", role: Role.BUYER, password: "2rUZar" },
  { email: "drodson5@angelfire.com", role: Role.SELLER, password: "J487lZ" },
  {
    email: "spimlott6@geocities.com",
    role: Role.BUYER,
    password: "7NvG1oV7dxYD",
  },
  { email: "tlowers7@fotki.com", role: Role.BUYER, password: "NJIqYKN" },
  { email: "nrikel8@amazon.com", role: Role.SELLER, password: "ZuiZEz" },
  { email: "zturfin9@jigsy.com", role: Role.SELLER, password: "Md3fR5" },
  { email: "fmintya@tmall.com", role: Role.SELLER, password: "NmvGM8" },
  { email: "shymorb@google.nl", role: Role.SELLER, password: "DnT9JAr1K3" },
  { email: "jkadarc@unblog.fr", role: Role.SELLER, password: "g6VS8LfwuGo" },
  {
    email: "edematteid@disqus.com",
    role: Role.BUYER,
    password: "zWj5ZwugTztn",
  },
  { email: "vaseefe@usda.gov", role: Role.SELLER, password: "Nh45UafxRoD" },
  {
    email: "ejewsonf@yellowpages.com",
    role: Role.SELLER,
    password: "fDh1mv3v4",
  },
  {
    email: "jschleswigholsteing@jimdo.com",
    role: Role.SELLER,
    password: "TzPNxR9s",
  },
  { email: "btrawinh@instagram.com", role: Role.SELLER, password: "OrAODYRiD" },
  { email: "wellinsi@disqus.com", role: Role.SELLER, password: "Leh99V0YdJqt" },
  {
    email: "gwalasj@microsoft.com",
    role: Role.SELLER,
    password: "qZrULorxSAC",
  },
  { email: "csturmk@homestead.com", role: Role.BUYER, password: "zFIHPmG" },
  { email: "vmillarl@smh.com.au", role: Role.BUYER, password: "VkJd3wZlX" },
  {
    email: "cforthm@hugedomains.com",
    role: Role.SELLER,
    password: "RgoH5t1WAlc",
  },
  {
    email: "tkedwardn@cocolog-nifty.com",
    role: Role.SELLER,
    password: "T3EDOjpBbGu",
  },
  { email: "bstreako@samsung.com", role: Role.SELLER, password: "JC2oY0ZAc" },
  { email: "epettitp@wisc.edu", role: Role.BUYER, password: "e29IwTmmQL" },
  { email: "dharteq@guardian.co.uk", role: Role.SELLER, password: "TGrMuP" },
  { email: "ewindaybankr@wired.com", role: Role.SELLER, password: "7VjC3Yim" },
  {
    email: "cpengilleys@independent.co.uk",
    role: Role.BUYER,
    password: "FlU8quXlxn",
  },
  { email: "sinsollt@sbwire.com", role: Role.SELLER, password: "OzQK157DdF5" },
  { email: "ikoenenu@oaic.gov.au", role: Role.BUYER, password: "FlStLtgv" },
  { email: "fdowningv@un.org", role: Role.BUYER, password: "KGD9LC4rE" },
  { email: "twarboyw@netlog.com", role: Role.SELLER, password: "QhPWqiM9WvVp" },
  { email: "lcreasex@reuters.com", role: Role.SELLER, password: "ngGQ2AfWmSk" },
  {
    email: "bridholey@odnoklassniki.ru",
    role: Role.BUYER,
    password: "z6viLFh",
  },
  { email: "lhitchamz@sogou.com", role: Role.SELLER, password: "VWs19V4ln0c" },
  { email: "lranklin10@reuters.com", role: Role.BUYER, password: "2vCiYr" },
  { email: "jbogaert11@prweb.com", role: Role.SELLER, password: "LsWuWkHme" },
  { email: "lmccook12@slideshare.net", role: Role.BUYER, password: "PfwPbAG" },
  {
    email: "kvalerio13@mayoclinic.com",
    role: Role.SELLER,
    password: "qUlJRi2Ty5",
  },
  {
    email: "atabbernor14@infoseek.co.jp",
    role: Role.SELLER,
    password: "ZO8gdHNkcrO",
  },
  { email: "dgibb15@icq.com", role: Role.SELLER, password: "M7gBUo" },
  {
    email: "cvautier16@nationalgeographic.com",
    role: Role.SELLER,
    password: "hUCsoYg0x",
  },
  { email: "tduffer17@spotify.com", role: Role.BUYER, password: "fYaMTfSvu" },
  { email: "hcoronas18@weibo.com", role: Role.SELLER, password: "R8gepgUx2" },
  { email: "lwildt19@ameblo.jp", role: Role.BUYER, password: "HTFMjD" },
  { email: "bcanning1a@china.com.cn", role: Role.BUYER, password: "qoMhTC" },
  {
    email: "ppattison1b@constantcontact.com",
    role: Role.SELLER,
    password: "Sdb31EFT17n",
  },
  { email: "aniblock1c@com.com", role: Role.SELLER, password: "j6IwuFYE" },
  { email: "bwethered1d@shop-pro.jp", role: Role.BUYER, password: "zozETuq" },
  { email: "bnewtown1e@upenn.edu", role: Role.BUYER, password: "Dris3k8" },
  {
    email: "bwyburn1f@angelfire.com",
    role: Role.SELLER,
    password: "K96hDe5oZ4",
  },
  { email: "bisaac1g@cnet.com", role: Role.BUYER, password: "wnmznhC" },
  { email: "ecorcut1h@cnet.com", role: Role.BUYER, password: "LalYGpGMNCkh" },
  { email: "hsor1i@dmoz.org", role: Role.SELLER, password: "PNUFcMuQ" },
  { email: "afaulks1j@va.gov", role: Role.BUYER, password: "WWYKEvE" },
  {
    email: "erodgers1k@whitehouse.gov",
    role: Role.SELLER,
    password: "SfKrmjziEmZ",
  },
  { email: "kwhye1l@ox.ac.uk", role: Role.SELLER, password: "iD22sz" },
  { email: "rkemery1m@github.com", role: Role.SELLER, password: "k0jjSK" },
  {
    email: "fjaye1n@opensource.org",
    role: Role.BUYER,
    password: "p8FEDx07uOnE",
  },
  { email: "gmichel1o@pbs.org", role: Role.SELLER, password: "pLKMRmsK" },
  {
    email: "jmaving1p@marketwatch.com",
    role: Role.SELLER,
    password: "3QglM1cm2Zr",
  },
  {
    email: "kleagas1q@craigslist.org",
    role: Role.SELLER,
    password: "V3eL1aqk7Q",
  },
  {
    email: "rmuskett1r@washingtonpost.com",
    role: Role.BUYER,
    password: "RjbcheFp7TL",
  },
  { email: "abuff1s@tinypic.com", role: Role.BUYER, password: "PWkbeR" },
  { email: "abierton1t@cpanel.net", role: Role.BUYER, password: "MezJSzlz" },
  {
    email: "pborsnall1u@bluehost.com",
    role: Role.BUYER,
    password: "im1gtaYTdDn",
  },
  { email: "efissenden1v@about.me", role: Role.SELLER, password: "dGpDtEf4j" },
  {
    email: "bbatistelli1w@issuu.com",
    role: Role.BUYER,
    password: "wAna3eflqy",
  },
  {
    email: "cbutteris1x@zdnet.com",
    role: Role.SELLER,
    password: "Tf0X5npdMHO",
  },
  {
    email: "smorrant1y@dropbox.com",
    role: Role.SELLER,
    password: "u67OGT1uQO",
  },
  { email: "rorigan1z@blinklist.com", role: Role.BUYER, password: "ixhqhLt" },
  { email: "agot20@youtu.be", role: Role.BUYER, password: "yB5BvmqqeHZ" },
  { email: "rdyas21@jimdo.com", role: Role.SELLER, password: "fbNLhmb9L" },
  {
    email: "ayarrow22@behance.net",
    role: Role.BUYER,
    password: "uIqrHgNC1DVi",
  },
  { email: "jdabnot23@xinhuanet.com", role: Role.BUYER, password: "33WVLqrqO" },
  { email: "sbirney24@wufoo.com", role: Role.BUYER, password: "oxmQDMwT" },
  { email: "amicheli25@apache.org", role: Role.BUYER, password: "AZg92c" },
  { email: "waldritt26@comsenz.com", role: Role.BUYER, password: "rSfDRMLM3" },
  { email: "avauter27@etsy.com", role: Role.SELLER, password: "0uWU2nAgwr" },
  { email: "tmoon28@utexas.edu", role: Role.BUYER, password: "15eLe5EeiL" },
  {
    email: "rklarzynski29@state.gov",
    role: Role.BUYER,
    password: "GUCfDDFEbjK",
  },
  {
    email: "ndsouza2a@cyberchimps.com",
    role: Role.BUYER,
    password: "qpHLet9Ud",
  },
  { email: "asleight2b@free.fr", role: Role.SELLER, password: "mdpZU3d" },
  {
    email: "swernher2c@storify.com",
    role: Role.SELLER,
    password: "uo4Zd2mewlG",
  },
  { email: "mkerman2d@yahoo.co.jp", role: Role.BUYER, password: "DPfaAM1K" },
  { email: "lmalthus2e@nsw.gov.au", role: Role.BUYER, password: "dw4f8V" },
  { email: "aborder2f@dropbox.com", role: Role.BUYER, password: "SQp71YNT02m" },
  { email: "emoro2g@bandcamp.com", role: Role.SELLER, password: "Dafo6ML" },
  { email: "flightbourn2h@hhs.gov", role: Role.BUYER, password: "aq1XrdLys5P" },
  { email: "abister2i@soup.io", role: Role.BUYER, password: "mLbWZUD8MkD" },
  {
    email: "bvasler2j@amazonaws.com",
    role: Role.BUYER,
    password: "aO659c5sFSn",
  },
  { email: "bkinnach2k@furl.net", role: Role.SELLER, password: "2ajaGmXpfT4" },
  {
    email: "jlegister2l@howstuffworks.com",
    role: Role.SELLER,
    password: "AAJtBfmSeONZ",
  },
  { email: "csneesby2m@cdbaby.com", role: Role.SELLER, password: "BkZlHWq" },
  { email: "ekillbey2n@senate.gov", role: Role.SELLER, password: "L26Nl24Sbk" },
  { email: "tlefley2o@netlog.com", role: Role.SELLER, password: "ULXhKSFCh" },
  {
    email: "cfittis2p@hostgator.com",
    role: Role.BUYER,
    password: "c7OmMSIJjo",
  },
  { email: "gismay2q@reuters.com", role: Role.BUYER, password: "oAWm95EpSs" },
  { email: "gmateja2r@mashable.com", role: Role.BUYER, password: "uvszGe" },
];
